# Generated by Django 6.1.1 on 2026-09-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('check_in', 'Checked In'), ('assessment', 'Assessment'), ('awaiting_approval', 'Awaiting Approval'), ('awaiting_parts', 'Awaiting Parts'), ('repair', 'Repair In Progress'), ('quality_check', 'Quality Check'), ('ready', 'Ready For Collection'), ('collected', 'Collected')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='workshop.staffprofile')),
                ('repair_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='workshop.repairjob')),
            ],
        ),
    ]
